---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-micro
spec:
  selector:
    matchLabels:
      app: second-micro
  replicas: 1
  template:
    metadata:
      labels:
        app: second-micro
    spec:
      containers:
        - name: second-micro
          image: second
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: second-micro
spec:
  selector:
    app: second-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
